<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMejkua6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMejkua6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMejkua6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMejkua6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMejkua6\appProdProjectContainer(array(
    'container.build_hash' => 'Mejkua6',
    'container.build_id' => 'ef506353',
    'container.build_time' => 1633563738,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMejkua6');
