<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerViwnklf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerViwnklf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerViwnklf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerViwnklf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerViwnklf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Viwnklf',
    'container.build_id' => 'ddedd745',
    'container.build_time' => 1627749555,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerViwnklf');
